name: Update Twitter RSS Feed

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install CA certificates
        run: sudo apt-get update && sudo apt-get install -y ca-certificates

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade certifi snscrape

      - name: Generate RSS feed
        run: |
          export SSL_CERT_FILE=$(python -m certifi)
          echo "Using cert bundle: $SSL_CERT_FILE"
          python generate_rss.py

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add rss.xml
          git commit -m "Update RSS feed" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:$(git rev-parse --abbrev-ref HEAD)
